version: '3.8'

services:
  pokenode:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - pokedb
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST:-pokedb}
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=pokedb
      - SERVER_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules

  pokedb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pokedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data-poke:/var/lib/mysql

volumes:
  db-data-poke:

